### ISSUE TITLE
open to a table-based view of the data?

### ISSUE THREAD

**Issue by gregsadetsky** [hobofan/collected-robotic-arms#3]
hi

congratulations on the great repo! I was looking to start one to document 0 - ~1k$ robotic arms and found this. I'd love to collaborate -- let me know if the below sounds interesting to you:

I think that it would be great to have a table view of the arms. I've thought of a few columns that would be great to have:
-- is the hardware open source (with link to code/BOM/STL files/etc.)
-- is there open source software (link to github repo, etc.)
-- how many DOF
-- maximum payload
-- is the arm available for purchase (as a kit and/or assembled) / link to online store
-- price
-- when was the information on this specific bot last updated

does that sound interesting?

perhaps there could be an additional file in the repo with this table? or it could be part of the readme?

thanks & looking forward!

**Comment by hobofan** [comment]
Glad that you found the repo helpful!

IIRC correctly, I tried that in the beginning, but once I started to add a few more columns, the table started to get really hard to read, at least when included in the standard README (I'm also not a big fan of some of the enormous tables that exist on Wikipedia for that reason). That's why I mostly focused on the current list format.

As for the approach with having it as a separate file, I'd be open to contributions like that. If you were to put it into a `.csv` or other table format, Github renders it differently and it might be more accessible (see [this table](https://github.com/multiformats/multiaddr/blob/c31d3998d6a395a1b1db0fadaf1bb3e4bc36ad3e/protocols.csv) as an example).

**Comment by gregsadetsky** [comment]
Fantastic, thank you very much! I think that a CSV makes sense as a complement to the information in the readme.

I'll clone this repo and create PRs against it with the CSV, and go from there?

I would imagine that you'd prefer the readme to have the same information than the CSV? i.e. any new arms should be documented in both places?

**Comment by gregsadetsky** [comment]
(sorry, closed this by mistake -- actually, I do think that it's ok to close?) :-)

**Comment by hobofan** [comment]
> I'll clone this repo and create PRs against it with the CSV, and go from there?
> 
> I would imagine that you'd prefer the readme to have the same information than the CSV? i.e. any new arms should be documented in both places?

As noted under [Contributing](https://github.com/hobofan/collected-robotic-arms/tree/744426588786cb7b131b07813a34d656810ba18d#contributing) in the README, the README is generated from data in the `src` directory. So in general the idea is that you add a way to generate the CSV from the raw data. The most straightforward way, given how the repo is currently set up would be to just create a second handlebars template that outputs the CSV (or via a small JS script). In the PR you should also include the generated CSV if possible.

I'd leave the issue open until a PR adding the functionality has been merged. :)

**Comment by gregsadetsky** [comment]
I hadn't seen the Contributing and the structured format source! That's awesome &&& I'm relieved at the thought of having to duplicate information ("Don't Repeat Yourself"..!) :-)

Fantastic on this issue / the PR. I'll let you know. Cheers!
